name: "repo 6dylan6_jdpr"
on:
  push:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: guojuna/git-repo-sync@master
      with:
        source_repo_url: git@github.com:6dylan6/jdpro.git
        source_branch: main
        dest_repo_url: git@github.com:andadmadm/tb_gitee.git
        dest_branch: jdpro
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
